spring:
  datasource:
    url: jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  flowable:
    check-process-definitions: true
    database-schema-update: true

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8888

flowable:
  check-process-definitions: true
  process-definition-location-prefix: classpath:/processes/